import "./globals.css";
import { DM_Sans, Inter } from "next/font/google";
import { Metadata } from "next";
import { Navbar } from "@/components/Navbar";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} bg-slate-800 text-white`}>
        <Navbar />
        <div className="px-16 mt-10">{children}</div>
      </body>
    </html>
  );
}
